service: app

provider:
  name: aws
  region: es-east-1

plugins:
  - ./vendor/bref/bref

functions:
  handler:
    name: wordpress-website
    handler: index.php
    # using bref plugin
    runtime: php-84-fpm
    # without bref plugin
    # runtime: provided.al2
    # layers:
    #   - "arn:aws:lambda:us-east-1:209497400698:layer:php-74-fpm:80"
    timeout: 60
    url: true
    environment:
      BREF_BINARY_RESPONSES: "1"

package:
  patterns:
    - "!node_modules/**"
    - "!tests/**"
